### ISSUE TITLE
multi-lines start with punctuation in python reportlab paragraph flowable

### ISSUE THREAD

**Issue by snowflake01986** [eduardocereto/reportlab#2]
I need to write a paragraph of Chinese characters on a pdf through reportlab. All works will except that, some lines starts with Chinese punctuations. Is there any parameters to avoid this problem?

**Comment by notonlycoffee** [comment]
Hi, same as my problem; have you solved it? please reply me! thx!

**Comment by snowflake01986** [comment]
I finally solved it by adding these punctuation to the list, according to which the program recognizes a char as a punctuation and forbid lines to start with these chars. I am sorry to forget the file name, but it really has been long time and it's pretty easy to find this file. Best wishes!
